id = "nginx"
name = "Nginx"
description = "Nginx syntax highlighting"
version = "0.0.1"
schema_version = 1
authors = ["Urs Gerber"]
repository = "https://github.com/HappyEmu/zed-nginx"

[grammars.nginx]
repository = "https://github.com/HappyEmu/tree-sitter-nginx"
rev = "3f01a77ac93eec3cb8a8604ac344e6b0bbb1f63c"
